-- ============================================================
-- SE2 DIAGNOSTIC & CLEANUP QUERIES — follow in order.
--
-- CONTEXT: The SE2 Formatted file has NO District column (only Zone) and a
-- single Name column (no Last Name). Prior to the import fix, Bulk Import read
-- Zone as District and left every surname blank, so rows landed under ZONE
-- names (ENUGU METROPOLITAN, EBONYI NORTH, ...) instead of "South East 2".
-- That is why "only 1 delegate" surfaced under South East 2 — the rest were
-- mis-filed under their zone names.
--
-- CONFIRMED HOST EVENT (24-Aug-2026): the SE2 rows live in the unified
-- "2026 Lagos National Convention" event. There is NO separate SE2 event.
--   event_id = 4b368055-89a5-4412-a3f0-648d1fd9090f
-- If an SE2-dedicated event is created later, replace the id below once.
-- ============================================================

\set se2_event '4b368055-89a5-4412-a3f0-648d1fd9090f'

-- 1) Event list + counts (for reference / reconfirmation).
SELECT e.event_id, e.name, count(d.delegate_id) AS delegates
FROM events e
LEFT JOIN delegates d ON d.event_id = e.event_id
GROUP BY e.event_id, e.name
ORDER BY delegates DESC;

-- 2) District distribution INSIDE the host event for the SE2-zone labels.
--    This shows exactly where the SE2 rows are sitting.
SELECT d.district, count(*) AS cnt
FROM delegates d
WHERE d.event_id = :'se2_event'
  AND UPPER(TRIM(d.district)) IN (
        'ENUGU METROPOLITAN', 'EBONYI NORTH', 'ENUGU WEST', 'ENUGU NORTH',
        'ENUGU EAST', 'EBONYI SOUTH', 'ENUGU SOUTH', 'EBONYI NORTH ZONE',
        'NSUKKA')
GROUP BY d.district
ORDER BY cnt DESC;

-- 2b) How many SE2-dedicated rows already exist in the host event
--     (should be ~0-2 — the ones that surfaced as "1 uploaded successfully").
SELECT d.district, count(*) AS cnt
FROM delegates d
WHERE d.event_id = :'se2_event'
  AND UPPER(TRIM(d.district)) IN ('SOUTH EAST 2', '')
GROUP BY d.district;

-- 3) The mis-filed SE2 rows in full (zone-as-district, mostly blank last name).
--    Review this list before deleting / re-importing.
SELECT d.delegate_id, d.district AS district_actual, d.chapter,
       d.title, d.first_name, d.last_name, d.phone, d.email
FROM delegates d
WHERE d.event_id = :'se2_event'
  AND UPPER(TRIM(d.district)) IN (
        'ENUGU METROPOLITAN', 'EBONYI NORTH', 'ENUGU WEST', 'ENUGU NORTH',
        'ENUGU EAST', 'EBONYI SOUTH', 'ENUGU SOUTH', 'EBONYI NORTH ZONE',
        'NSUKKA')
ORDER BY d.district, d.chapter NULLS FIRST, d.last_name NULLS FIRST;

-- ============================================================
-- FINAL FINDINGS + RECOMMENDED RUNBOOK  (updated after live-DB checks)
-- ============================================================
-- FINDINGS:
--  * Queries 2 / B returned ZERO rows under the ENUGU*/EBONYI* zone names.
--  * Only ~1-2 "South East 2"/blank rows exist, and neither is from the SE2
--    file (UCHE EDUM / GATE WAY and Mark Idenyi have no match in the source),
--    so they are unrelated leftover rows — safe to ignore or delete.
--  * Conclusion: the SE2 bulk import wrote essentially NO delegates (the
--    earlier "1 uploaded successfully" was a stray/test row, not file data).
--    There are NO mis-filed SE2 rows to clean up.
--  * The live import RPC (import_delegates_batch_merge) accepts distinct rows
--    and will insert all 292 canonical rows into a fresh/active event.
--
-- RUNBOOK (final — clean re-import, no cleanup needed):
-- 1. Confirm the host event is ACTIVE (is_active = true) so writes are allowed:
--    UPDATE events SET is_active = true
--    WHERE event_id = '4b368055-89a5-4412-a3f0-648d1fd9090f';
-- 2. Make sure you are using the DEPLOYED build that includes the SE2 import
--    fix (ImportModule mapper hardening + preprocessor output). If in doubt,
--    redeploy from the repo so mappedCsvData produces the corrected rows.
-- 3. In the app, set the ACTIVE EVENT to "2026 Lagos National Convention".
-- 4. On Import Data -> Bulk Delegate Import, upload:
--    ...\manual regs\Districts Manual Reg Files 15-08-26\SE2_Registrations_Canonical.csv
--    (generated by preprocess_se2_csv.py — all 292 rows District="South East 2",
--     first/last names split, phones normalized).
-- 5. Verify: in the Master List, filter District to "South East 2" and confirm
--    ~292 delegates with proper surnames appear.
-- ============================================================
